apiVersion: v1
kind: Service
metadata:
  name: devopsprojectv2-service
spec:
  selector:
    app: devopsprojectv2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer